language: php

notifications:
  email:
    recipients:
      - brendan.heywood@gmail.com
      - marcus@boon.mx
      - danielroperto@catalyst-au.net

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.5
 - 7.0

env:
  - DB=pgsql MOODLE_BRANCH=MOODLE_26_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_27_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_28_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_29_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE MOODLE_REPO=https://github.com/kenneth-hendricks/moodle-fs-api.git
  - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=pgsql MOODLE_BRANCH=master
  - DB=mysqli MOODLE_BRANCH=MOODLE_26_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_27_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_28_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_29_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=mysqli MOODLE_BRANCH=master
  - DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE MOODLE_REPO=https://github.com/kenneth-hendricks/moodle-fs-api.git


matrix:
  include:
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=master
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=master
  exclude:
    - php: 5.5
      env: DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
    - php: 5.5
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_26_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_27_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_28_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_29_STABLE
    - php: 5.5
      env: DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
    - php: 5.5
      env: DB=pgsql MOODLE_BRANCH=master
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_26_STABLE
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_27_STABLE
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_28_STABLE
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_29_STABLE


before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci dev-master
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat

